# apiVersion: v1
# kind: Secret
# metadata:
#   name: postgres-secrets
#   namespace: sonarqube
# type: Opaque
# data:
#   username: cG9zdGdyZXNhZG1pbg==
#   password: YWRtaW4xMjM=
# ---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: postgres-secrets
  namespace: sonarqube
spec:
  backendType: ibmcloudSecretsManager
  keyByName: true
  data:
    - key: SONARQUBE_POSTGRESQL_CREDENTIALS
      property: username
      name: POSTGRES_USER
      secretType: username_password
    - key: SONARQUBE_POSTGRESQL_CREDENTIALS
      property: password
      name: POSTGRES_PASSWORD
      secretType: username_password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: sonarqube
spec:
  storageClassName: ibmc-file-gold
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: postgres-secrets
          ports:
            - containerPort: 5432
          
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
          
      restartPolicy: Always
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sonarqube
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres