-- liquibase formatted sql

-- changeset harish:storetable
CREATE TABLE LIQ_SCHEMA.store(
        store_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        store_name VARCHAR(150) NOT NULL,
        city_id INT NOT NULL,
        PRIMARY KEY (store_id)
);
-- rollback DROP TABLE LIQ_SCHEMA.store;